/*
 * main.c — Muad'dib Entry Point
 *
 * WHY A SEPARATE main.c and NOT put main() in parser.y?
 * Bison lets you put main() at the bottom of the .y file (in the
 * user code section). Many examples online do this. We chose NOT to
 * because:
 *   1. Separation of concerns — the parser parses, main runs the show
 *   2. main.c is the place where we handle I/O setup (file vs stdin)
 *   3. It's easier to test the parser separately if main is separate
 */

#include <stdio.h>
#include <stdlib.h>
#include "symbols.h"

/*
 * yyparse() is generated by Bison. Calling it starts the parse.
 * It calls yylex() (from Flex) internally to get tokens.
 */
extern int yyparse(void);

/*
 * yyin is Flex's global input file pointer.
 * By default it reads from stdin.
 * We can redirect it to a file by setting yyin before calling yyparse().
 */
extern FILE* yyin;

int main(int argc, char* argv[]) {
    /*
     * WHY support both file input and stdin?
     * During development, stdin is convenient for quick tests.
     * For real programs (like test.mdb), we want to pass a filename.
     * Supporting both makes the tool flexible.
     *
     * WHY argc > 1 and NOT argc == 2?
     * argc > 1 means "at least one argument was provided".
     * We use argv[1] as the filename. If more arguments are given,
     * we ignore them — keeping it simple.
     */
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
        if (yyin == NULL) {
            fprintf(stderr,
                "[Muad'dib] Error: cannot open file '%s'\n", argv[1]);
            return 1;
        }
        printf("=== Muad'dib: running '%s' ===\n\n", argv[1]);
    } else {
        yyin = stdin;
        printf("=== Muad'dib: reading from stdin (Ctrl+D to end) ===\n\n");
    }

    /*
     * WHY check the return value of yyparse()?
     * yyparse() returns 0 on success and 1 on error.
     * Checking it lets us set the process exit code correctly.
     * A process that exits with code 0 = success.
     * A process that exits with code 1 = something went wrong.
     * This matters when you chain tools (like in a Makefile or CI pipeline).
     */
    int result = yyparse();

    /*
     * WHY call symbol_free()?
     * Technically unnecessary — the OS reclaims memory on exit.
     * But it's good practice and keeps Valgrind happy.
     * Also shows we thought about memory: we own the heap, we clean it.
     */
    symbol_free();

    if (argc > 1) {
        fclose(yyin);
    }

    if (result == 0) {
        printf("\n=== Muad'dib: execution complete ===\n");
    } else {
        fprintf(stderr, "\n=== Muad'dib: execution failed ===\n");
    }

    return result;
}
